export const contributionsParamsComponents = [
  { name: 'dampingFp', type: 'uint256' },
  { name: 'toleranceFp', type: 'uint256' },
  { name: 'maxIterations', type: 'uint32' },
  { name: 'minWeightFp', type: 'uint256' },
  { name: 'maxWeightFp', type: 'uint256' },
  { name: 'trustShareFp', type: 'uint256' },
  { name: 'trustDecayFp', type: 'uint256' },
  { name: 'trustedSeeds', type: 'address[]' },
  { name: 'precisionScale', type: 'uint256' },
  { name: 'weightFieldIndex', type: 'uint32' },
  { name: 'roundStart', type: 'uint64' },
  { name: 'roundEnd', type: 'uint64' },
  { name: 'unacceptedMultFp', type: 'uint256' },
  { name: 'collaboratorMultFp', type: 'uint256' },
  { name: 'minRaterRepFp', type: 'uint256' },
  { name: 'evaluatorCarveoutBps', type: 'uint32' },
  { name: 'totalPool', type: 'uint256' },
  { name: 'claimSchemaUid', type: 'bytes32' },
  { name: 'responseSchemaUid', type: 'bytes32' },
  { name: 'valuationSchemaUid', type: 'bytes32' },
] as const

export const contributionsParamsControllerAbi = [
  {
    type: 'event',
    name: 'ContributionsParamsUpdated',
    inputs: [
      { name: 'instanceId', type: 'bytes32', indexed: true },
      { name: 'version', type: 'uint64', indexed: true },
      { name: 'paramsHash', type: 'bytes32', indexed: true },
      { name: 'previousParamsHash', type: 'bytes32', indexed: false },
      {
        name: 'params',
        type: 'tuple',
        indexed: false,
        components: contributionsParamsComponents,
      },
      { name: 'evidenceURI', type: 'string', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'instanceId',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'snapshot',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'eas',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'registry',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'version',
    inputs: [],
    outputs: [{ name: '', type: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'currentParamsHash',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getContributionsParams',
    inputs: [],
    outputs: [
      { name: '', type: 'tuple', components: contributionsParamsComponents },
    ],
    stateMutability: 'view',
  },
] as const
