packages:
  - frontend
  - indexer
  - packages/eas-offchain-client
  - services/eas-offchain-relay

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bufferutil
  - esbuild
  - keccak
  - secp256k1
  - sharp
  - utf-8-validate
