# https://taskfile.dev/installation/
# - npm install -g @go-task/cli
version: "3"

silent: true

dotenv: [".env"]

includes:
  # Project-specific taskfiles
  core:
    taskfile: ./taskfile/core.yml
    flatten: true
  build: ./taskfile/build.yml
  forge: ./taskfile/eas-forge.yml
  merkle: ./taskfile/merkle.yml
  services: ./taskfile/services.yml
  trustgraph: ./taskfile/trustgraph.yml
  env:
    taskfile: ./taskfile/env.yml
    flatten: true

vars:
  # Default endpoints
  RPC_URL: '{{.RPC_URL | default "http://127.0.0.1:8545"}}'
  IPFS_ENDPOINT: '{{.IPFS_ENDPOINT | default "http://127.0.0.1:5001"}}'
  IPFS_GATEWAY: '{{.IPFS_GATEWAY | default "http://127.0.0.1:8080/ipfs/"}}'

tasks:
  default:
    cmds:
      - task --list-all

  help:
    cmds:
      - task --list-all

  setup:
    desc: "Install initial dependencies"
    cmds:
      - |
        echo "📦 Installing pnpm dependencies..."
        pnpm install
        echo "📦 Installing forge dependencies..."
        forge install
        echo "✅ Dependencies installed"

  start-all-local:
    desc: "Start all local services (anvil, IPFS, WARG, Jaeger, prometheus)"
    deps: [setup-env]
    cmds:
      - task: services:start-all
